services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    command: node build/server/index.js
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - '3000:3000'
